### ISSUE TITLE
Uninitialized Property Access Exception

### ISSUE THREAD

**Issue by IzhanAli** [arwazkhan189/BookHub#3]
```
kotlin.UninitializedPropertyAccessException: lateinit property recyclerAdapter has not been initialized
	at me.arwazkhan.bookhub.fragment.DashboardFragment.onOptionsItemSelected(DashboardFragment.kt:163)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3226)
	at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:416)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:358)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25919)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```

**Comment by arwazkhan189** [comment]
Hey, @IzhanAli  Check from your side .. the app working fine 
you can check the live demo  [link](https://appetize.io/embed/nmda4g8dfmb5kgxvf2w0973yy0?device=nexus5&scale=75&orientation=portrait&osVersion=8.1)
